# Generated by Django 2.2.7 on 2019-12-18 13:42

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'About me',
                'verbose_name_plural': 'About me',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('technologies', models.TextField(choices=[('html', 'Html'), ('css', 'Css'), ('js', 'javascript'), ('py', 'python'), ('et', 'electron')], default='----')),
                ('project_image', models.ImageField(upload_to='projects')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.TextField(choices=[('Front End', (('js', 'Javascript'), ('html', 'Html'), ('css', 'CSS'))), ('Back End', (('py', 'Python'), ('node', 'Node'))), ('Design', (('cad', 'Conputer Aided Design'), ('ps', 'Adobe Pototshop'), ('ai', 'Adobe Illustrator'))), ('unknown', 'Unknown')])),
                ('skill', models.TextField(verbose_name='Add Skill')),
            ],
            options={
                'verbose_name_plural': 'skills',
            },
        ),
    ]
