# Generated by Django 2.2.7 on 2019-12-20 06:19

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191220_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpicture',
            name='postid',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_image',
            field=models.ImageField(default='/assets/projects_placeholder.jpg', upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('html', 'Html'), ('js', 'Javacript'), ('node', 'Node Js'), ('gulp', 'Gulp Js'), ('cs', 'Css'), ('py', 'Python'), ('java', 'Java'), ('Elec', 'Electron'), ('Elec', 'Electron'), ('ps', 'Adobe Photoshop'), ('xd', 'Adoved XD')], max_length=44),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostPicture',
        ),
    ]
