# Generated by Django 2.2.7 on 2019-12-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191220_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='social_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField(blank=True)),
                ('behance', models.URLField(blank=True)),
                ('dribble', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='front_page_image',
            field=models.ImageField(null=True, upload_to='yoo'),
        ),
        migrations.AddField(
            model_name='about',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_image',
            field=models.ImageField(blank=True, upload_to='projects'),
        ),
    ]
