# Generated by Django 2.2.7 on 2019-12-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191220_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('github', models.URLField(blank=True)),
                ('behance', models.URLField(blank=True)),
                ('dribble', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='social_links',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Me', 'verbose_name_plural': 'About'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='user_email',
        ),
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='details',
            name='linkss',
            field=models.ManyToManyField(blank=True, to='core.About'),
        ),
    ]
