# Generated by Django 2.2.7 on 2019-12-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191220_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='linkss',
        ),
        migrations.AddField(
            model_name='about',
            name='First_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='Last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='details',
            name='about',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.About'),
        ),
        migrations.AlterField(
            model_name='about',
            name='front_page_image',
            field=models.ImageField(blank=True, upload_to='yoo'),
        ),
    ]
