# Generated by Django 2.2.7 on 2019-12-20 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191220_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='details',
            name='about',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='boo', to='core.About'),
        ),
    ]
