# Generated by Django 2.2.7 on 2019-12-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191220_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profile_image',
            field=models.ImageField(default='', upload_to='about'),
        ),
    ]
