# Generated by Django 2.2.7 on 2019-12-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_about_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='other',
            field=models.TextField(blank=True),
        ),
    ]
