# Generated by Django 2.2.7 on 2019-12-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_details_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='front_page_image',
            field=models.ImageField(blank=True, default='', upload_to='about'),
        ),
        migrations.AlterField(
            model_name='about',
            name='profile_image',
            field=models.ImageField(blank=True, default='', upload_to='about'),
        ),
    ]
