# Generated by Django 2.2.7 on 2019-12-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_foo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
        migrations.RemoveField(
            model_name='details',
            name='other',
        ),
    ]
