# Generated by Django 2.2.7 on 2019-12-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20191220_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
