# Generated by Django 2.2.7 on 2019-12-20 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_about_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='about',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.About'),
        ),
    ]
