# Generated by Django 2.2.7 on 2019-12-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20191220_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='behance',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='dribble',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='details',
        ),
    ]
