# Generated by Django 2.2.7 on 2020-01-05 16:19

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20191220_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='added_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_image_1',
            field=models.ImageField(blank=True, upload_to='projects'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_image_2',
            field=models.ImageField(blank=True, upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('html', 'Html'), ('js', 'Javacript'), ('node', 'Node Js'), ('gulp', 'Gulp Js'), ('cs', 'Css'), ('py', 'Python'), ('java', 'Java'), ('Elec', 'Electron'), ('ps', 'Adobe Photoshop'), ('wp', 'Wordpress'), ('xd', 'Adobe XD')], max_length=42),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Front End', (('Javascript', 'Javascript'), ('html', 'Html'), ('css', 'CSS'))), ('Back End', (('Python', 'Python'), ('Node', 'Node'), ('java', 'java'), ('php', 'php'))), ('Design', (('cad', 'Computer Aided Design'), ('solidworks', 'solidworks'), ('blender', 'blender'), ('adobe', 'Adobe Creative Suite'))), ('unknown', 'Unknown')], max_length=33),
        ),
    ]
