# Generated by Django 2.2.7 on 2020-01-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200105_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project_image_2',
            new_name='project_image2',
        ),
    ]
