# Generated by Django 2.2.7 on 2020-01-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200105_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_image2',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_image_3',
            field=models.ImageField(blank=True, upload_to='projects'),
        ),
    ]
