# Generated by Django 2.2.7 on 2020-01-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200105_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_image_2',
            field=models.ImageField(blank=True, upload_to='projects'),
        ),
    ]
