# Generated by Django 2.2.7 on 2020-01-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_projects_project_image_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_image_2',
            field=models.ImageField(upload_to='projects'),
        ),
    ]
