# Generated by Django 2.2.7 on 2020-01-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200105_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
    ]
