# Generated by Django 2.2.7 on 2020-01-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200105_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skill',
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_image',
            field=models.ImageField(blank=True, upload_to='projects'),
        ),
    ]
