# Generated by Django 2.2.7 on 2020-01-06 18:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200106_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('html', 'html'), ('cs', 'Css'), ('Javascript', 'Javascript'), ('Python', 'Python'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('DECEMBER', 'December')], max_length=49),
        ),
    ]
