# Generated by Django 2.2.7 on 2020-01-07 23:25

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200106_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='phone_number',
            field=models.IntegerField(default=4400000000000, max_length=14),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Front End', (('Javascript', 'Javascript'), ('html', 'Html'), ('css', 'CSS'), ('electron', 'Electron'))), ('Back End', (('Python', 'Python'), ('django', 'Django'), ('node js', 'Node js'), ('java', 'Java'), ('php', 'Php'))), ('Design', (('cad', 'CAD'), ('solidworks', 'Solidworks'), ('blender', 'Blender'), ('adobe', 'Adobe Creative Suite'), ('photoshop', 'Photoshop'), ('illustartor', 'illustartor'), ('Corel Draw', 'Corel Draw'))), ('unknown', 'Unknown')], max_length=33),
        ),
    ]
